### ISSUE TITLE
a lot of errors

### ISSUE THREAD

**Issue by devrajashwin** [Ganapati/Crawlic#8]
root@localhost:~/Downloads/Crawlic-master# ./crawlic.py --url http://www.*************.com
 _____                    _ _
/  __ \                  | (_)
| /  \/_ __ __ ___      _| |_  ___
| |   | '__/ _` \ \ /\ / / | |/ __|
| \__/\ | | (_| |\ V  V /| | | (__
 \____/_|  \__,_| \_/\_/ |_|_|\___|

###################################

[*] Scan http://www.*****************.com using techniques rtfgd
[*] Probe host http://www. *****************.com
[*] Starting robots.txt search
   [+]  /wp-admin/
[*] Starting temp file search
[*] Starting folder search
   [+] /admin/
Traceback (most recent call last):
  File "./crawlic.py", line 395, in <module>
    main()
  File "./crawlic.py", line 382, in main
    scanFolders(args.url, args.folders, page_not_found_pattern)
  File "./crawlic.py", line 245, in scanFolders
    searchFolders(url, folders, page_not_found_pattern)
  File "./crawlic.py", line 177, in searchFolders
    verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='**********.com', port=80): Max retries exceeded with url: /config/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc2b484a710>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by Ganapati** [comment]
Hi devrajashwin !

It's seems your target doesn't respond during the tests, maybe mod_evasive or a mod_security conf ?
I've added responses message in this case (ex: "[!] Connection error during robots.txt parsing").

This way, crawlic doesn't crash and process the next technique.

My tests are ok, but let me know if the bug is still here.

**Comment by devrajashwin** [comment]
ok thanx for the help ....
i appreciate it nice project ,
i will test once again and let u know about it
